"""MambaIR 원본 arch_util.py에서 필요한 유틸리티 함수 추출

Original source: https://github.com/csguoh/MambaIR
File: basicsr/archs/arch_util.py

MambaIRv2Light에서 사용하는 함수들만 추출하여 독립적으로 사용 가능하게 함.
"""

import collections.abc
import math
import torch
import warnings
from itertools import repeat
from torch import nn as nn
from torch.nn import init as init
from torch.nn.modules.batchnorm import _BatchNorm


# =============================================================================
# From PyTorch / timm - tuple 변환 유틸리티
# =============================================================================

def _ntuple(n):
    """n-tuple 생성 함수
    
    Example:
        to_2tuple(3) -> (3, 3)
        to_2tuple((3, 4)) -> (3, 4)
    """
    def parse(x):
        if isinstance(x, collections.abc.Iterable):
            return x
        return tuple(repeat(x, n))
    return parse


to_1tuple = _ntuple(1)
to_2tuple = _ntuple(2)
to_3tuple = _ntuple(3)
to_4tuple = _ntuple(4)
to_ntuple = _ntuple


# =============================================================================
# Weight Initialization - trunc_normal_
# =============================================================================

def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    """Truncated normal 분포로 텐서 초기화 (gradient 없이)
    
    From: https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/layers/weight_init.py
    """
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn(
            'mean is more than 2 std from [a, b] in nn.init.trunc_normal_. '
            'The distribution of values may be incorrect.',
            stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        low = norm_cdf((a - mean) / std)
        up = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [low, up], then translate to [2l-1, 2u-1].
        tensor.uniform_(2 * low - 1, 2 * up - 1)

        # Use inverse cdf transform for normal distribution to get truncated standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    r"""Truncated normal 분포로 텐서 채우기
    
    From: https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/layers/weight_init.py

    값들은 정규분포 N(mean, std^2)에서 추출되며,
    [a, b] 범위 밖의 값들은 범위 내로 다시 추출됨.

    Args:
        tensor: n-dimensional torch.Tensor
        mean: 정규분포의 평균
        std: 정규분포의 표준편차
        a: 최소 cutoff 값
        b: 최대 cutoff 값

    Examples:
        >>> w = torch.empty(3, 5)
        >>> trunc_normal_(w)
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


# =============================================================================
# Default Weight Initialization
# =============================================================================

@torch.no_grad()
def default_init_weights(module_list, scale=1, bias_fill=0, **kwargs):
    """네트워크 가중치 초기화
    
    Args:
        module_list (list[nn.Module] | nn.Module): 초기화할 모듈(들)
        scale (float): 초기화된 가중치 스케일, 특히 residual block용. Default: 1.
        bias_fill (float): bias 채울 값. Default: 0
        kwargs (dict): 초기화 함수의 다른 인자들
    """
    if not isinstance(module_list, list):
        module_list = [module_list]
    for module in module_list:
        for m in module.modules():
            if isinstance(m, nn.Conv2d):
                init.kaiming_normal_(m.weight, **kwargs)
                m.weight.data *= scale
                if m.bias is not None:
                    m.bias.data.fill_(bias_fill)
            elif isinstance(m, nn.Linear):
                init.kaiming_normal_(m.weight, **kwargs)
                m.weight.data *= scale
                if m.bias is not None:
                    m.bias.data.fill_(bias_fill)
            elif isinstance(m, _BatchNorm):
                init.constant_(m.weight, 1)
                if m.bias is not None:
                    m.bias.data.fill_(bias_fill)


# =============================================================================
# Upsample Module (MambaIR에서 사용)
# =============================================================================

class Upsample(nn.Sequential):
    """Upsample 모듈
    
    Args:
        scale (int): 스케일 팩터. 지원: 2^n 과 3.
        num_feat (int): 중간 feature 채널 수
    """

    def __init__(self, scale, num_feat):
        m = []
        if (scale & (scale - 1)) == 0:  # scale = 2^n
            for _ in range(int(math.log(scale, 2))):
                m.append(nn.Conv2d(num_feat, 4 * num_feat, 3, 1, 1))
                m.append(nn.PixelShuffle(2))
        elif scale == 3:
            m.append(nn.Conv2d(num_feat, 9 * num_feat, 3, 1, 1))
            m.append(nn.PixelShuffle(3))
        else:
            raise ValueError(f'scale {scale} is not supported. Supported scales: 2^n and 3.')
        super(Upsample, self).__init__(*m)


# =============================================================================
# Residual Block (일부 MambaIR 버전에서 사용)
# =============================================================================

class ResidualBlockNoBN(nn.Module):
    """BN 없는 Residual block
    
    구조:
        ---Conv-ReLU-Conv-+-
         |________________|

    Args:
        num_feat (int): 중간 feature 채널 수. Default: 64.
        res_scale (float): Residual scale. Default: 1.
        pytorch_init (bool): True면 pytorch 기본 init 사용. Default: False.
    """

    def __init__(self, num_feat=64, res_scale=1, pytorch_init=False):
        super(ResidualBlockNoBN, self).__init__()
        self.res_scale = res_scale
        self.conv1 = nn.Conv2d(num_feat, num_feat, 3, 1, 1, bias=True)
        self.conv2 = nn.Conv2d(num_feat, num_feat, 3, 1, 1, bias=True)
        self.relu = nn.ReLU(inplace=True)

        if not pytorch_init:
            default_init_weights([self.conv1, self.conv2], 0.1)

    def forward(self, x):
        identity = x
        out = self.conv2(self.relu(self.conv1(x)))
        return identity + out * self.res_scale
